baseURL = 'https://stunning-sprinkles.netlify.app'
languageCode = 'en-us'
title = 'ICT 302 Project'
theme = 'ananke'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Products'
    pageRef = '/products'
    weight = 20
  [[menus.main]]
    name = 'Services'
    pageRef = '/services'
    weight = 30