baseURL = 'https://stunning-sprinkles.netlify.app'
languageCode = 'en-us'
title = 'Nailed It'
theme = 'ananke_safe'

sectionPagesMenu = 'nav'

[params]
custom_css = ["custom.css"]

[menus]
[[menus.nav]]
   name = 'Home'
   pageref = '/'
   weight = 10
  
[[menus.nav]]
   name = 'Looking to Hire?'
   pageref = '/Hofer-Page'
   weight = 20
[[menus.nav]]
    name = 'Seeking Work?'
    pageRef = '/larson-page'
    weight = 30
