baseURL = 'https://stunning-sprinkles.netlify.app'
languageCode = 'en-us'
title = 'ICT 302 Project'
<<<<<<< HEAD
theme = 'ananke'
=======
theme = 'ananke2'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

>>>>>>> 44dfa867afc7e3619c7c559e51b0c6d46e26c8e4
