baseURL = 'https://stunning-sprinkles.netlify.app'
languageCode = 'en-us'
title = 'ICT 302 Project'
theme = 'ananke2'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Posts'
    pageRef = 'larson-post'
    weight = 20
  [[menus.main]]
    name = 'Page'
    pageRef = 'hofer-page'
    weight = 30
