baseURL = 'https://stunning-sprinkles.netlify.app'
languageCode = 'en-us'
title = 'ICT 302 Project'
theme = 'ananke2'

[menus]
  [[menus.main]]
    name = 'Larson Page'
    pageRef = '/larson-page'
    weight = 10
  
 
